### ISSUE TITLE
Where can I check preview of this project?

### ISSUE THREAD

**Issue by zero734kr** [Saebasol/Lily#2]
Is there already a website that hosts this?

Or I need to download and run on my computer to view?

Are there any plans to use some hosting platforms like `` Vercel``, ``Heroku``, ``VPS``, ``etc``?

Mention me as @zero734kr when you close this issue.

**Comment by zero734kr** [comment]
@SaidBySolo

**Comment by SaidBySolo** [comment]
First you need to open the [backend](https://github.com/Saebasol/Heliotrope) first.

Then modify the following [items](https://github.com/Saebasol/Lily/blob/develop/src/routes/Container.js#L10) as appropriate

and when all of the above are completed, run ``npm start'' after ``npm install''

It is currently not released and you can see that there is nothing in the [main](https://github.com/Saebasol/Lily/tree/main) branch.

There are no plans to host so far.
